[package]
name = "k_means_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.0.0"
ndarray = "0.15.3"
rand = "0.8.4"
